### ISSUE TITLE
`cargo info` with offline should give better error message

### ISSUE THREAD

**Issue by hi-rustin** [hi-rustin/cargo-information#13]
Right now:

```console
error: could not find `vlq-bij` in registry `https://github.com/rust-lang/crates.io-index`
```

Expected:

```console
error: attempting to make an HTTP request, but --offline was specified
```

**Comment by hi-rustin** [comment]
It seems this behavior is expected. 

Because if you try `cargo install aj --offline` it will tell you:
```log
❯ cargo install aj --offline
error: could not find `aj` in registry `crates-io` with version `*`
```

So I think it is consistent with the Cargo's behavior.

**Comment by epage** [comment]
Agreed, if people want this improved, then they should open an issue against cargo.

However, I do wonder about mixed situations
- Entry is in the Index but we don't have the `.crate`
- (future) We have Index and `.crate` but we can't do API calls to the registry
