### ISSUE TITLE
How should we handle the difference in dependency name vs package name?

### ISSUE THREAD

**Issue by epage** [hi-rustin/cargo-information#24]
Currently, we show the package name.  Which is more meangful to the viewer?

**Comment by hi-rustin** [comment]
Do you mean should we display the possible `explicit_name_in_toml` name?

**Comment by epage** [comment]
Correct.  When listing dependencies, how should we handle that split.

**Comment by epage** [comment]
As the tool is focused on showing packages and we just choose defaults from a workspace, I would say we should not be mucking with the dependency name.  I see this similarly out of scope as `--manifest-path`
