### ISSUE TITLE
Should we default to a rust-version compatible package when one isn't in a workspace?

### ISSUE THREAD

**Issue by epage** [hi-rustin/cargo-information#28]
So I run `cargo info clap`
- In a workspace but I'm not using it yet
- Out of a workspace

It might be useful for us to default to an MSRV compatible version.

Some choices (which we might pick different answers in and out of a workspace)
- Check the MSRV of the parent directories package
- Check the lowest MSRV of all workspace members
- Check `rustc --version`

We could have `--ignore-rust-version` support

**Comment by hi-rustin** [comment]
Closed by https://github.com/hi-rustin/cargo-information/pull/74
