### ISSUE TITLE
Support full version requirements

### ISSUE THREAD

**Issue by PaulDance** [hi-rustin/cargo-information#99]
Dear maintainer,

As a potentially-orthogonal continuation to #98, it would be nice as well if the version specification was extended to accept fully-capable SemVer version requirements, i.e. something that `semver::VersionReq` parses. It would be used in the same context: determining the latest version that `cargo install` would actually install.

Currently, only Cargo's package specs are used and they are a bit lightweight: only rough selections may be used. Furthermore, from what I can see in `src/ops/info.rs` and `src/ops/view.rs`, the filtering is done entirely offline and on all available versions, so this shouldn't be too big of a change either, right?

Cheers,
Paul.

**Comment by epage** [comment]
For myself, I think this will be more used more for looking up libraries and being consistent with the spec syntax of cargo would give the most benefit.

**Comment by PaulDance** [comment]
> I think this will be more used more for looking up libraries

True.

> being consistent with the spec syntax of cargo would give the most benefit.

Isn't a version requirement a strict superset of specs, though?

**Comment by hi-rustin** [comment]
> Aren't version requirements a strict superset of specs, though?

This is Cargo Package ID spec: https://doc.rust-lang.org/cargo/reference/pkgid-spec.html

**Comment by PaulDance** [comment]
Oh yes, I forgot about URLs. Thanks for the link.

I guess it means the change would be too destructive and not aligned with the command's intentions, then? Otherwise, maybe have it in another option or would it add too much complexity in order to detect the compatibility between the mandatory spec that does not have a version and the optional version requirement?

**Comment by epage** [comment]
Choice comes at a cost (maintainability, overloading users)  and we have to weigh out the benefits of that cost.  imo we are aligned with the standard meaning of the `--package` flag at is used in most of cargo.  So long as people know what versions exist, they can find the information they want for a version.  I don't see enough of a need (only use case being: "predicting what cargo install will install") to justify it.

**Comment by PaulDance** [comment]
Yeah, that sounds fair. I'll look at other options, then.

Thanks for the cordial discussion and quick replies anyway!
